FROM golang:latest

# Pasta de trabalho padrão da app
WORKDIR /app

# Comando para deixar o container rodando (Fica lendo comandos que esta sendo mandado para /dev/null)
CMD ["tail", "-f", "/dev/null"] 