POST http://localhost:8000/users
Content-Type: "application/json"

{
    "name": "Joao",
    "email": "joao@gmail.com",
    "password": "Teligam"
}

###
POST http://localhost:8000/users/generate_token

{
    "email": "joao@gmail.com",
    "password": "Teligam"
}